-- Auto-generated by MonarchAegis Controller
settings {
    logfile = "/logs/monarchaegis.log",
    statusFile = "/logs/monarchaegis.status",
    statusInterval = 10
}

-- name: mock_target_1
sync {
    default.rsync,
    source = "/source_data/backups",
    target = "user@192.168.1.50:/mnt/backups",
    delay = 15,
    rsync = {
        update = true,
        _extra = {"--size-only"}
    }
}
